import time
from datetime import datetime
from pymongo import MongoClient

time.sleep(5)

client = MongoClient("mongodb://mongo:27017/")
db = client["ecommerce"]

user_sessions = [
    {"session_id": "sess_0001", "user_id": "user_1",  "start_time": datetime(2026, 1, 5,  9,  0), "end_time": datetime(2026, 1, 5,  9, 45), "pages_visited": ["/home", "/products", "/cart"],              "device": {"type": "mobile",  "os": "Android"}, "actions": ["login", "view_product", "add_to_cart"]},
    {"session_id": "sess_0002", "user_id": "user_2",  "start_time": datetime(2026, 1, 7, 14, 30), "end_time": datetime(2026, 1, 7, 15, 10), "pages_visited": ["/home", "/checkout"],                       "device": {"type": "desktop", "os": "Windows"}, "actions": ["login", "checkout"]},
    {"session_id": "sess_0003", "user_id": "user_3",  "start_time": datetime(2026, 1, 10, 11, 0), "end_time": datetime(2026, 1, 10, 11, 50), "pages_visited": ["/products", "/products/42", "/cart"],       "device": {"type": "mobile",  "os": "iOS"},     "actions": ["view_product", "add_to_cart", "logout"]},
    {"session_id": "sess_0004", "user_id": "user_4",  "start_time": datetime(2026, 1, 12, 16, 0), "end_time": datetime(2026, 1, 12, 16, 25), "pages_visited": ["/orders", "/profile"],                     "device": {"type": "desktop", "os": "macOS"},   "actions": ["login", "search"]},
    {"session_id": "sess_0005", "user_id": "user_5",  "start_time": datetime(2026, 1, 15,  8, 0), "end_time": datetime(2026, 1, 15,  9,  5), "pages_visited": ["/home", "/products", "/products/42"],      "device": {"type": "mobile",  "os": "Android"}, "actions": ["login", "view_product"]},
    {"session_id": "sess_0006", "user_id": "user_1",  "start_time": datetime(2026, 1, 18, 10, 0), "end_time": datetime(2026, 1, 18, 10, 40), "pages_visited": ["/cart", "/checkout"],                      "device": {"type": "mobile",  "os": "Android"}, "actions": ["add_to_cart", "checkout"]},
    {"session_id": "sess_0007", "user_id": "user_6",  "start_time": datetime(2026, 1, 20, 13, 0), "end_time": datetime(2026, 1, 20, 13, 55), "pages_visited": ["/home", "/products"],                      "device": {"type": "desktop", "os": "Windows"}, "actions": ["login", "search", "view_product"]},
    {"session_id": "sess_0008", "user_id": "user_7",  "start_time": datetime(2026, 1, 25,  9, 0), "end_time": datetime(2026, 1, 25,  9, 30), "pages_visited": ["/profile", "/orders"],                     "device": {"type": "mobile",  "os": "iOS"},     "actions": ["login", "logout"]},

    {"session_id": "sess_0009", "user_id": "user_2",  "start_time": datetime(2026, 2, 2, 10,  0), "end_time": datetime(2026, 2, 2, 10, 50), "pages_visited": ["/home", "/products", "/cart", "/checkout"], "device": {"type": "desktop", "os": "Windows"}, "actions": ["login", "add_to_cart", "checkout"]},
    {"session_id": "sess_0010", "user_id": "user_3",  "start_time": datetime(2026, 2, 5, 14,  0), "end_time": datetime(2026, 2, 5, 14, 35), "pages_visited": ["/products/42", "/cart"],                   "device": {"type": "mobile",  "os": "iOS"},     "actions": ["view_product", "add_to_cart"]},
    {"session_id": "sess_0011", "user_id": "user_8",  "start_time": datetime(2026, 2, 8,  9, 30), "end_time": datetime(2026, 2, 8, 10, 15), "pages_visited": ["/home", "/products", "/products/42"],      "device": {"type": "desktop", "os": "macOS"},   "actions": ["login", "search", "view_product"]},
    {"session_id": "sess_0012", "user_id": "user_9",  "start_time": datetime(2026, 2, 10, 16, 0), "end_time": datetime(2026, 2, 10, 16, 45), "pages_visited": ["/cart", "/checkout", "/orders"],           "device": {"type": "mobile",  "os": "Android"}, "actions": ["checkout", "logout"]},
    {"session_id": "sess_0013", "user_id": "user_4",  "start_time": datetime(2026, 2, 12, 11, 0), "end_time": datetime(2026, 2, 12, 11, 20), "pages_visited": ["/home"],                                  "device": {"type": "desktop", "os": "Windows"}, "actions": ["login", "search"]},
    {"session_id": "sess_0014", "user_id": "user_10", "start_time": datetime(2026, 2, 14,  8, 0), "end_time": datetime(2026, 2, 14,  9,  0), "pages_visited": ["/products", "/products/42", "/cart"],      "device": {"type": "mobile",  "os": "iOS"},     "actions": ["view_product", "add_to_cart", "checkout"]},
    {"session_id": "sess_0015", "user_id": "user_5",  "start_time": datetime(2026, 2, 17, 13, 0), "end_time": datetime(2026, 2, 17, 13, 40), "pages_visited": ["/profile", "/orders"],                    "device": {"type": "desktop", "os": "macOS"},   "actions": ["login", "logout"]},
    {"session_id": "sess_0016", "user_id": "user_6",  "start_time": datetime(2026, 2, 19, 10, 0), "end_time": datetime(2026, 2, 19, 11, 10), "pages_visited": ["/home", "/products", "/cart"],             "device": {"type": "mobile",  "os": "Android"}, "actions": ["login", "view_product", "add_to_cart"]},
    {"session_id": "sess_0017", "user_id": "user_7",  "start_time": datetime(2026, 2, 22, 15, 0), "end_time": datetime(2026, 2, 22, 15, 25), "pages_visited": ["/checkout", "/orders"],                   "device": {"type": "desktop", "os": "Windows"}, "actions": ["checkout"]},

    {"session_id": "sess_0018", "user_id": "user_1",  "start_time": datetime(2026, 3, 1, 10,  0), "end_time": datetime(2026, 3, 1, 10, 55), "pages_visited": ["/home", "/products", "/products/42"],      "device": {"type": "mobile",  "os": "Android"}, "actions": ["login", "view_product", "add_to_cart"]},
    {"session_id": "sess_0019", "user_id": "user_8",  "start_time": datetime(2026, 3, 3, 14,  0), "end_time": datetime(2026, 3, 3, 14, 30), "pages_visited": ["/cart", "/checkout"],                      "device": {"type": "desktop", "os": "macOS"},   "actions": ["checkout", "logout"]},
    {"session_id": "sess_0020", "user_id": "user_9",  "start_time": datetime(2026, 3, 5,  9,  0), "end_time": datetime(2026, 3, 5,  9, 50), "pages_visited": ["/home", "/products"],                      "device": {"type": "mobile",  "os": "iOS"},     "actions": ["login", "search"]},
    {"session_id": "sess_0021", "user_id": "user_2",  "start_time": datetime(2026, 3, 7, 16,  0), "end_time": datetime(2026, 3, 7, 16, 40), "pages_visited": ["/products/42", "/cart", "/checkout"],       "device": {"type": "desktop", "os": "Windows"}, "actions": ["view_product", "add_to_cart", "checkout"]},
    {"session_id": "sess_0022", "user_id": "user_10", "start_time": datetime(2026, 3, 7, 11,  0), "end_time": datetime(2026, 3, 7, 11, 15), "pages_visited": ["/profile"],                                "device": {"type": "mobile",  "os": "Android"}, "actions": ["login", "logout"]},
    {"session_id": "sess_0023", "user_id": "user_3",  "start_time": datetime(2026, 3, 9, 10,  0), "end_time": datetime(2026, 3, 9, 11,  5), "pages_visited": ["/home", "/products", "/cart", "/orders"],  "device": {"type": "mobile",  "os": "iOS"},     "actions": ["login", "view_product", "add_to_cart", "checkout"]},
    {"session_id": "sess_0024", "user_id": "user_4",  "start_time": datetime(2026, 3, 9, 13,  0), "end_time": datetime(2026, 3, 9, 13, 45), "pages_visited": ["/products", "/products/42"],               "device": {"type": "desktop", "os": "macOS"},   "actions": ["search", "view_product"]},
    {"session_id": "sess_0025", "user_id": "user_5",  "start_time": datetime(2026, 3, 9, 15,  0), "end_time": datetime(2026, 3, 9, 15, 30), "pages_visited": ["/cart", "/checkout", "/orders"],           "device": {"type": "mobile",  "os": "Android"}, "actions": ["add_to_cart", "checkout"]},
]

event_logs = [
    {"event_id": "evt_1001", "timestamp": datetime(2026, 1, 5,  9,  5), "event_type": "click",     "details": {"page": "/products/42",  "product_id": "prod_101", "user_id": "user_1"}},
    {"event_id": "evt_1002", "timestamp": datetime(2026, 1, 5,  9, 15), "event_type": "page_view", "details": {"page": "/cart",         "product_id": None,        "user_id": "user_1"}},
    {"event_id": "evt_1003", "timestamp": datetime(2026, 1, 7, 14, 35), "event_type": "purchase",  "details": {"page": "/checkout",     "product_id": "prod_110", "user_id": "user_2"}},
    {"event_id": "evt_1004", "timestamp": datetime(2026, 1, 10, 11, 5), "event_type": "click",     "details": {"page": "/products/42",  "product_id": "prod_142", "user_id": "user_3"}},
    {"event_id": "evt_1005", "timestamp": datetime(2026, 1, 12, 16, 5), "event_type": "search",    "details": {"page": "/products",     "product_id": None,        "user_id": "user_4"}},
    {"event_id": "evt_1006", "timestamp": datetime(2026, 1, 15,  8, 10),"event_type": "page_view", "details": {"page": "/home",         "product_id": None,        "user_id": "user_5"}},
    {"event_id": "evt_1007", "timestamp": datetime(2026, 1, 18, 10, 5), "event_type": "click",     "details": {"page": "/products/42",  "product_id": "prod_101", "user_id": "user_1"}},
    {"event_id": "evt_1008", "timestamp": datetime(2026, 1, 20, 13, 10),"event_type": "scroll",    "details": {"page": "/products",     "product_id": None,        "user_id": "user_6"}},
    {"event_id": "evt_1009", "timestamp": datetime(2026, 1, 20, 13, 20),"event_type": "click",     "details": {"page": "/products/42",  "product_id": "prod_155", "user_id": "user_6"}},
    {"event_id": "evt_1010", "timestamp": datetime(2026, 1, 25,  9,  5),"event_type": "page_view", "details": {"page": "/orders",       "product_id": None,        "user_id": "user_7"}},
    {"event_id": "evt_1011", "timestamp": datetime(2026, 2, 2, 10,  5), "event_type": "purchase",  "details": {"page": "/checkout",     "product_id": "prod_120", "user_id": "user_2"}},
    {"event_id": "evt_1012", "timestamp": datetime(2026, 2, 2, 10, 20), "event_type": "page_view", "details": {"page": "/orders",       "product_id": None,        "user_id": "user_2"}},
    {"event_id": "evt_1013", "timestamp": datetime(2026, 2, 5, 14,  5), "event_type": "click",     "details": {"page": "/products/42",  "product_id": "prod_142", "user_id": "user_3"}},
    {"event_id": "evt_1014", "timestamp": datetime(2026, 2, 8,  9, 35), "event_type": "search",    "details": {"page": "/products",     "product_id": None,        "user_id": "user_8"}},
    {"event_id": "evt_1015", "timestamp": datetime(2026, 2, 8,  9, 50), "event_type": "click",     "details": {"page": "/products/42",  "product_id": "prod_133", "user_id": "user_8"}},
    {"event_id": "evt_1016", "timestamp": datetime(2026, 2, 10, 16, 5), "event_type": "purchase",  "details": {"page": "/checkout",     "product_id": "prod_133", "user_id": "user_9"}},
    {"event_id": "evt_1017", "timestamp": datetime(2026, 2, 12, 11, 5), "event_type": "page_view", "details": {"page": "/home",         "product_id": None,        "user_id": "user_4"}},
    {"event_id": "evt_1018", "timestamp": datetime(2026, 2, 14,  8, 10),"event_type": "click",     "details": {"page": "/products/42",  "product_id": "prod_101", "user_id": "user_10"}},
    {"event_id": "evt_1019", "timestamp": datetime(2026, 2, 14,  8, 40),"event_type": "purchase",  "details": {"page": "/checkout",     "product_id": "prod_101", "user_id": "user_10"}},
    {"event_id": "evt_1020", "timestamp": datetime(2026, 2, 17, 13, 5), "event_type": "scroll",    "details": {"page": "/products",     "product_id": None,        "user_id": "user_5"}},
    {"event_id": "evt_1021", "timestamp": datetime(2026, 2, 19, 10, 15),"event_type": "click",     "details": {"page": "/products/42",  "product_id": "prod_177", "user_id": "user_6"}},
    {"event_id": "evt_1022", "timestamp": datetime(2026, 2, 19, 10, 50),"event_type": "error",     "details": {"page": "/checkout",     "product_id": None,        "user_id": "user_6"}},
    {"event_id": "evt_1023", "timestamp": datetime(2026, 2, 22, 15, 5), "event_type": "purchase",  "details": {"page": "/checkout",     "product_id": "prod_188", "user_id": "user_7"}},
    {"event_id": "evt_1024", "timestamp": datetime(2026, 3, 1, 10, 10), "event_type": "click",     "details": {"page": "/products/42",  "product_id": "prod_101", "user_id": "user_1"}},
    {"event_id": "evt_1025", "timestamp": datetime(2026, 3, 1, 10, 35), "event_type": "page_view", "details": {"page": "/cart",         "product_id": None,        "user_id": "user_1"}},
    {"event_id": "evt_1026", "timestamp": datetime(2026, 3, 3, 14, 15), "event_type": "purchase",  "details": {"page": "/checkout",     "product_id": "prod_110", "user_id": "user_8"}},
    {"event_id": "evt_1027", "timestamp": datetime(2026, 3, 5,  9,  5), "event_type": "search",    "details": {"page": "/products",     "product_id": None,        "user_id": "user_9"}},
    {"event_id": "evt_1028", "timestamp": datetime(2026, 3, 7, 16,  5), "event_type": "click",     "details": {"page": "/products/42",  "product_id": "prod_142", "user_id": "user_2"}},
    {"event_id": "evt_1029", "timestamp": datetime(2026, 3, 7, 16, 20), "event_type": "purchase",  "details": {"page": "/checkout",     "product_id": "prod_142", "user_id": "user_2"}},
    {"event_id": "evt_1030", "timestamp": datetime(2026, 3, 9, 10, 30), "event_type": "page_view", "details": {"page": "/home",         "product_id": None,        "user_id": "user_3"}},
]

support_tickets = [
    {"ticket_id": "ticket_701", "user_id": "user_1",  "status": "resolved",    "issue_type": "payment",         "messages": [{"sender": "user",    "message": "Не могу оплатить заказ.",         "timestamp": datetime(2026, 1, 6,  9,  0)}, {"sender": "support", "message": "Проверьте данные карты.", "timestamp": datetime(2026, 1, 6, 10,  0)}], "created_at": datetime(2026, 1, 6,  9,  0), "updated_at": datetime(2026, 1, 6, 22,  0)},
    {"ticket_id": "ticket_702", "user_id": "user_2",  "status": "closed",      "issue_type": "delivery",        "messages": [{"sender": "user",    "message": "Где мой заказ?",                  "timestamp": datetime(2026, 1, 8, 11,  0)}, {"sender": "support", "message": "Заказ в пути.",           "timestamp": datetime(2026, 1, 8, 12,  0)}], "created_at": datetime(2026, 1, 8, 11,  0), "updated_at": datetime(2026, 1, 9, 15,  0)},
    {"ticket_id": "ticket_703", "user_id": "user_3",  "status": "resolved",    "issue_type": "account",         "messages": [{"sender": "user",    "message": "Не могу войти в аккаунт.",        "timestamp": datetime(2026, 1, 11, 8,  0)}, {"sender": "support", "message": "Сбросьте пароль.",       "timestamp": datetime(2026, 1, 11, 9,  0)}], "created_at": datetime(2026, 1, 11, 8,  0), "updated_at": datetime(2026, 1, 11, 18, 0)},
    {"ticket_id": "ticket_704", "user_id": "user_4",  "status": "open",        "issue_type": "product_quality", "messages": [{"sender": "user",    "message": "Товар не соответствует описанию.", "timestamp": datetime(2026, 1, 15, 14, 0)}],                                                                                                                          "created_at": datetime(2026, 1, 15, 14, 0), "updated_at": datetime(2026, 1, 15, 14, 0)},
    {"ticket_id": "ticket_705", "user_id": "user_5",  "status": "in_progress", "issue_type": "return",          "messages": [{"sender": "user",    "message": "Хочу вернуть товар.",             "timestamp": datetime(2026, 1, 20, 10, 0)}, {"sender": "support", "message": "Оформляем возврат.",     "timestamp": datetime(2026, 1, 20, 12, 0)}], "created_at": datetime(2026, 1, 20, 10, 0), "updated_at": datetime(2026, 1, 21, 10, 0)},
    {"ticket_id": "ticket_706", "user_id": "user_6",  "status": "closed",      "issue_type": "payment",         "messages": [{"sender": "user",    "message": "Дважды списали деньги.",          "timestamp": datetime(2026, 1, 22,  9, 0)}, {"sender": "support", "message": "Возврат выполнен.",      "timestamp": datetime(2026, 1, 22, 11, 0)}], "created_at": datetime(2026, 1, 22,  9, 0), "updated_at": datetime(2026, 1, 22, 20, 0)},
    {"ticket_id": "ticket_707", "user_id": "user_7",  "status": "resolved",    "issue_type": "delivery",        "messages": [{"sender": "user",    "message": "Посылка повреждена.",             "timestamp": datetime(2026, 1, 27, 13, 0)}, {"sender": "support", "message": "Оформим замену.",        "timestamp": datetime(2026, 1, 27, 14, 0)}], "created_at": datetime(2026, 1, 27, 13, 0), "updated_at": datetime(2026, 1, 28, 16, 0)},
    {"ticket_id": "ticket_708", "user_id": "user_8",  "status": "resolved",    "issue_type": "account",         "messages": [{"sender": "user",    "message": "Не приходит письмо с кодом.",     "timestamp": datetime(2026, 2, 3, 10,  0)}, {"sender": "support", "message": "Проверьте папку спам.",  "timestamp": datetime(2026, 2, 3, 10, 30)}], "created_at": datetime(2026, 2, 3, 10,  0), "updated_at": datetime(2026, 2, 3, 16,  0)},
    {"ticket_id": "ticket_709", "user_id": "user_9",  "status": "closed",      "issue_type": "payment",         "messages": [{"sender": "user",    "message": "Промокод не работает.",           "timestamp": datetime(2026, 2, 6, 14,  0)}, {"sender": "support", "message": "Срок промокода истёк.",  "timestamp": datetime(2026, 2, 6, 15,  0)}], "created_at": datetime(2026, 2, 6, 14,  0), "updated_at": datetime(2026, 2, 7,  9,  0)},
    {"ticket_id": "ticket_710", "user_id": "user_10", "status": "in_progress", "issue_type": "product_quality", "messages": [{"sender": "user",    "message": "Пришёл не тот цвет.",            "timestamp": datetime(2026, 2, 9,  9,  0)}, {"sender": "support", "message": "Готовим замену.",        "timestamp": datetime(2026, 2, 9, 10,  0)}], "created_at": datetime(2026, 2, 9,  9,  0), "updated_at": datetime(2026, 2, 10, 12, 0)},
    {"ticket_id": "ticket_711", "user_id": "user_1",  "status": "resolved",    "issue_type": "return",          "messages": [{"sender": "user",    "message": "Хочу отменить заказ.",            "timestamp": datetime(2026, 2, 13, 11, 0)}, {"sender": "support", "message": "Заказ отменён.",         "timestamp": datetime(2026, 2, 13, 12, 0)}], "created_at": datetime(2026, 2, 13, 11, 0), "updated_at": datetime(2026, 2, 13, 20, 0)},
    {"ticket_id": "ticket_712", "user_id": "user_2",  "status": "open",        "issue_type": "delivery",        "messages": [{"sender": "user",    "message": "Статус не обновляется.",          "timestamp": datetime(2026, 2, 18, 15, 0)}],                                                                                                                          "created_at": datetime(2026, 2, 18, 15, 0), "updated_at": datetime(2026, 2, 18, 15, 0)},
    {"ticket_id": "ticket_713", "user_id": "user_3",  "status": "closed",      "issue_type": "payment",         "messages": [{"sender": "user",    "message": "Не прошёл платёж.",              "timestamp": datetime(2026, 2, 22,  9, 0)}, {"sender": "support", "message": "Попробуйте другую карту.","timestamp": datetime(2026, 2, 22, 10, 0)}], "created_at": datetime(2026, 2, 22,  9, 0), "updated_at": datetime(2026, 2, 22, 22, 0)},
    {"ticket_id": "ticket_714", "user_id": "user_4",  "status": "resolved",    "issue_type": "account",         "messages": [{"sender": "user",    "message": "Хочу удалить аккаунт.",           "timestamp": datetime(2026, 2, 25, 10, 0)}, {"sender": "support", "message": "Отправили инструкцию.",  "timestamp": datetime(2026, 2, 25, 11, 0)}], "created_at": datetime(2026, 2, 25, 10, 0), "updated_at": datetime(2026, 2, 25, 18, 0)},
    {"ticket_id": "ticket_715", "user_id": "user_5",  "status": "open",        "issue_type": "product_quality", "messages": [{"sender": "user",    "message": "Товар сломан.",                   "timestamp": datetime(2026, 3, 2, 10,  0)}],                                                                                                                          "created_at": datetime(2026, 3, 2, 10,  0), "updated_at": datetime(2026, 3, 2, 10,  0)},
    {"ticket_id": "ticket_716", "user_id": "user_6",  "status": "in_progress", "issue_type": "return",          "messages": [{"sender": "user",    "message": "Хочу вернуть обувь.",             "timestamp": datetime(2026, 3, 4, 14,  0)}, {"sender": "support", "message": "Уточните причину.",      "timestamp": datetime(2026, 3, 4, 15,  0)}], "created_at": datetime(2026, 3, 4, 14,  0), "updated_at": datetime(2026, 3, 5, 10,  0)},
    {"ticket_id": "ticket_717", "user_id": "user_7",  "status": "resolved",    "issue_type": "payment",         "messages": [{"sender": "user",    "message": "Зависла оплата.",                 "timestamp": datetime(2026, 3, 6,  9,  0)}, {"sender": "support", "message": "Платёж подтверждён.",   "timestamp": datetime(2026, 3, 6, 10,  0)}], "created_at": datetime(2026, 3, 6,  9,  0), "updated_at": datetime(2026, 3, 6, 18,  0)},
    {"ticket_id": "ticket_718", "user_id": "user_8",  "status": "closed",      "issue_type": "delivery",        "messages": [{"sender": "user",    "message": "Заказ доставлен не в тот адрес.", "timestamp": datetime(2026, 3, 7, 11,  0)}, {"sender": "support", "message": "Организуем повторную доставку.", "timestamp": datetime(2026, 3, 7, 13, 0)}], "created_at": datetime(2026, 3, 7, 11,  0), "updated_at": datetime(2026, 3, 8, 15,  0)},
    {"ticket_id": "ticket_719", "user_id": "user_9",  "status": "open",        "issue_type": "account",         "messages": [{"sender": "user",    "message": "Аккаунт заблокирован.",           "timestamp": datetime(2026, 3, 9,  8,  0)}],                                                                                                                          "created_at": datetime(2026, 3, 9,  8,  0), "updated_at": datetime(2026, 3, 9,  8,  0)},
    {"ticket_id": "ticket_720", "user_id": "user_10", "status": "resolved",    "issue_type": "product_quality", "messages": [{"sender": "user",    "message": "Истёк срок годности.",            "timestamp": datetime(2026, 3, 9, 10,  0)}, {"sender": "support", "message": "Оформляем возврат.",     "timestamp": datetime(2026, 3, 9, 11,  0)}], "created_at": datetime(2026, 3, 9, 10,  0), "updated_at": datetime(2026, 3, 9, 22,  0)},
]

user_recommendations = [
    {"user_id": "user_1",  "recommended_products": ["prod_101", "prod_142", "prod_155", "prod_188"], "last_updated": datetime(2026, 3, 8, 10, 0)},
    {"user_id": "user_2",  "recommended_products": ["prod_110", "prod_120", "prod_133"],             "last_updated": datetime(2026, 3, 8, 10, 0)},
    {"user_id": "user_3",  "recommended_products": ["prod_142", "prod_101", "prod_177", "prod_199"], "last_updated": datetime(2026, 3, 8, 10, 0)},
    {"user_id": "user_4",  "recommended_products": ["prod_155", "prod_110"],                         "last_updated": datetime(2026, 3, 8, 10, 0)},
    {"user_id": "user_5",  "recommended_products": ["prod_188", "prod_133", "prod_120"],             "last_updated": datetime(2026, 3, 8, 10, 0)},
    {"user_id": "user_6",  "recommended_products": ["prod_177", "prod_101", "prod_155", "prod_142"], "last_updated": datetime(2026, 3, 8, 10, 0)},
    {"user_id": "user_7",  "recommended_products": ["prod_188", "prod_110", "prod_199"],             "last_updated": datetime(2026, 3, 8, 10, 0)},
    {"user_id": "user_8",  "recommended_products": ["prod_133", "prod_120", "prod_101"],             "last_updated": datetime(2026, 3, 8, 10, 0)},
    {"user_id": "user_9",  "recommended_products": ["prod_142", "prod_188", "prod_177"],             "last_updated": datetime(2026, 3, 8, 10, 0)},
    {"user_id": "user_10", "recommended_products": ["prod_101", "prod_133", "prod_155", "prod_120"], "last_updated": datetime(2026, 3, 8, 10, 0)},
]

moderation_queue = [
    {"review_id": "rev_501", "user_id": "user_1",  "product_id": "prod_101", "review_text": "Отличный товар, рекомендую!",              "rating": 5, "moderation_status": "approved",  "flags": [],                                      "submitted_at": datetime(2026, 1, 7,  12, 0)},
    {"review_id": "rev_502", "user_id": "user_2",  "product_id": "prod_110", "review_text": "Быстрая доставка, всё пришло в порядке.",  "rating": 4, "moderation_status": "approved",  "flags": ["verified_purchase"],                   "submitted_at": datetime(2026, 1, 10, 15, 0)},
    {"review_id": "rev_503", "user_id": "user_3",  "product_id": "prod_142", "review_text": "Качество среднее, но цена оправдана.",     "rating": 3, "moderation_status": "approved",  "flags": [],                                      "submitted_at": datetime(2026, 1, 13, 10, 0)},
    {"review_id": "rev_504", "user_id": "user_4",  "product_id": "prod_155", "review_text": "Не соответствует описанию.",               "rating": 2, "moderation_status": "pending",   "flags": ["contains_images"],                     "submitted_at": datetime(2026, 1, 16, 14, 0)},
    {"review_id": "rev_505", "user_id": "user_5",  "product_id": "prod_120", "review_text": "Буду заказывать снова!",                  "rating": 5, "moderation_status": "approved",  "flags": ["verified_purchase"],                   "submitted_at": datetime(2026, 1, 21, 11, 0)},
    {"review_id": "rev_506", "user_id": "user_6",  "product_id": "prod_133", "review_text": "Пришёл с дефектом.",                      "rating": 1, "moderation_status": "pending",   "flags": ["contains_images", "potential_spam"],   "submitted_at": datetime(2026, 1, 23,  9, 0)},
    {"review_id": "rev_507", "user_id": "user_7",  "product_id": "prod_188", "review_text": "Хорошее соотношение цены и качества.",    "rating": 4, "moderation_status": "approved",  "flags": [],                                      "submitted_at": datetime(2026, 2, 3,  13, 0)},
    {"review_id": "rev_508", "user_id": "user_8",  "product_id": "prod_101", "review_text": "Очень доволен покупкой.",                 "rating": 5, "moderation_status": "approved",  "flags": ["verified_purchase"],                   "submitted_at": datetime(2026, 2, 7,  10, 0)},
    {"review_id": "rev_509", "user_id": "user_9",  "product_id": "prod_177", "review_text": "Товар пришёл без инструкции.",             "rating": 3, "moderation_status": "pending",   "flags": [],                                      "submitted_at": datetime(2026, 2, 11, 16, 0)},
    {"review_id": "rev_510", "user_id": "user_10", "product_id": "prod_199", "review_text": "Отличное качество, советую!",             "rating": 5, "moderation_status": "approved",  "flags": ["verified_purchase"],                   "submitted_at": datetime(2026, 2, 15,  9, 0)},
    {"review_id": "rev_511", "user_id": "user_1",  "product_id": "prod_142", "review_text": "Ожидал большего.",                        "rating": 2, "moderation_status": "rejected",  "flags": ["potential_spam"],                      "submitted_at": datetime(2026, 2, 20, 12, 0)},
    {"review_id": "rev_512", "user_id": "user_2",  "product_id": "prod_133", "review_text": "Заказывал уже второй раз — не подвёл.",   "rating": 5, "moderation_status": "approved",  "flags": ["verified_purchase"],                   "submitted_at": datetime(2026, 2, 24, 14, 0)},
    {"review_id": "rev_513", "user_id": "user_3",  "product_id": "prod_110", "review_text": "Размер не совпадает с таблицей.",         "rating": 2, "moderation_status": "pending",   "flags": ["contains_images"],                     "submitted_at": datetime(2026, 3, 1,  10, 0)},
    {"review_id": "rev_514", "user_id": "user_4",  "product_id": "prod_120", "review_text": "Всё отлично, доставили быстро.",          "rating": 5, "moderation_status": "approved",  "flags": ["verified_purchase"],                   "submitted_at": datetime(2026, 3, 4,  11, 0)},
    {"review_id": "rev_515", "user_id": "user_5",  "product_id": "prod_188", "review_text": "Качество оставляет желать лучшего.",      "rating": 1, "moderation_status": "pending",   "flags": ["potential_spam", "contains_images"],   "submitted_at": datetime(2026, 3, 7,  15, 0)},
    {"review_id": "rev_516", "user_id": "user_6",  "product_id": "prod_155", "review_text": "Хороший продукт за эти деньги.",          "rating": 4, "moderation_status": "approved",  "flags": [],                                      "submitted_at": datetime(2026, 3, 8,  10, 0)},
    {"review_id": "rev_517", "user_id": "user_7",  "product_id": "prod_177", "review_text": "Немного разочарован упаковкой.",          "rating": 3, "moderation_status": "approved",  "flags": [],                                      "submitted_at": datetime(2026, 3, 9,   9, 0)},
]

collections = {
    "UserSessions":       user_sessions,
    "EventLogs":          event_logs,
    "SupportTickets":     support_tickets,
    "UserRecommendations": user_recommendations,
    "ModerationQueue":    moderation_queue,
}

for name, docs in collections.items():
    db[name].drop()
    db[name].insert_many(docs)
    print(f"{name}: {len(docs)} docs inserted")

print("Done.")
